### ISSUE TITLE
Elaborar a solução para o projeto

### ISSUE THREAD

**Issue by gabibguedes** [deeplearningunb/ViraLataCaramelo#2]
**Tarefas**
- [x] Pesquisar algoritmos de identificação de cães e gatos e outros CNNs
- [x] Elaborar a arquitetura da rede neural (quantas camadas serão utilizadas)
- [x] Escolher as funções de ativação

**Comment by gabrielalbino** [comment]
#### Pesquisar algoritmos de identificação de cães e gatos e outros CNNs

Foi realizado uma pesquisa, achando um artigo muito interessante que ajuou na arquitetura da rede neural, escolha das funções de ativações, entre outros. http://deeplearningbook.com.br/reconhecimento-de-imagens-com-redes-neurais-convolucionais-em-python-parte-4/
